os: osx
language: generic
osx_image: xcode9.3

python:
  - 2.7
  - 3.5

env:
  matrix:
    - PYVERSION=python2  PYSMT_SOLVER="None"
    - PYVERSION=python2  PYSMT_SOLVER="msat"
    - PYVERSION=python2  PYSMT_SOLVER="z3"
    - PYVERSION=python2  PYSMT_SOLVER="yices"
    - PYVERSION=python3  PYSMT_SOLVER="msat"
    - PYVERSION=python3  PYSMT_SOLVER="z3"
    - PYVERSION=python3  PYSMT_SOLVER="yices"

install:
  - "brew update"
  - "brew --version"
  - "brew --prefix"
  - "brew outdated python || brew upgrade python"
  - "brew install python@2"
  - "export PYTHON_EXE=`brew --prefix`/bin/${PYVERSION}"
  - "echo ${PYTHON_EXE}"
  - "brew install swig"
  - "${PYTHON_EXE} -m pip install --upgrade pip"
  - "${PYTHON_EXE} -m pip install --user six"
  - "${PYTHON_EXE} -m pip install --user nose"
  - "${PYTHON_EXE} -m pip install --user urllib3"
  - "export BINDINGS_FOLDER=${HOME}/python_bindings/${PYSMT_SOLVER}"
  - "mkdir -p ${BINDINGS_FOLDER}"
  - "${PYTHON_EXE} install.py --confirm-agreement --bindings-path ${BINDINGS_FOLDER}"
  - "eval `${PYTHON_EXE} install.py --env --bindings-path ${BINDINGS_FOLDER}`"


script:
  - echo ${PYTHON_EXE}
  - "${PYTHON_EXE} --version"
  - "echo ${PYTHONPATH}"
  - "${PYTHON_EXE} install.py --check"
  - "${PYTHON_EXE} -mnose pysmt -v"
  - if [ "${PYSMT_SOLVER}" == "all" ]; then python install.py --msat --conf --force; cp -v $(find ~/.smt_solvers/ -name mathsat -type f) /tmp/mathsat; (for ex in `ls examples/*.py`; do echo $ex; python $ex || exit $?; done); fi
