language: python

sudo: false

cache:
  apt: true
  directories:
  - ${HOME}/.smt_solvers/btor
  - ${HOME}/.cache/pip
  - ${HOME}/python_bindings/all
  - ${HOME}/python_bindings/msat
  - ${HOME}/python_bindings/z3
  - ${HOME}/python_bindings/cvc4
  - ${HOME}/python_bindings/yices
  - ${HOME}/python_bindings/bdd
  - ${HOME}/python_bindings/picosat
  - ${HOME}/python_bindings/btor

addons:
  apt:
    packages:
    - python-setuptools
    - python-nose
    - python-pip
    - python-dev
    - make
    - build-essential
    - swig
    - libgmp-dev
    - autoconf
    - libtool
    - wget
    - curl
    - libboost-dev
    - python3-dev

python:
  - 2.6


# Multiple envs will cause multiple build across multiple python versions.
# We test the following:
# 1. PySMT w/o solvers
# 2. PySMT with one solver at the time
#
env:
  matrix:
    - PYSMT_SOLVER="all"
    - PYSMT_SOLVER="None"
    - PYSMT_SOLVER="msat"
    - PYSMT_SOLVER="z3"
    - PYSMT_SOLVER="cvc4"
    - PYSMT_SOLVER="yices"
    - PYSMT_SOLVER="bdd"
    - PYSMT_SOLVER="picosat"
    - PYSMT_SOLVER="btor"
    - PYSMT_SOLVER="msat_wrap"

matrix:
  fast_finish: true

install:
  - "pip install six"
  - "pip install unittest2"
  - if [ "${PYSMT_SOLVER}" == "all" ] || [ "${PYSMT_SOLVER}" == "btor" ]; then pip install cython; fi
  - "export BINDINGS_FOLDER=${HOME}/python_bindings/${PYSMT_SOLVER}"
  - "mkdir -p ${BINDINGS_FOLDER}"
  - "python install.py --confirm-agreement --bindings-path ${BINDINGS_FOLDER}"
  - "eval `python install.py --env --bindings-path ${BINDINGS_FOLDER}`"

script:
  - "echo ${PYTHONPATH}"
  - "python install.py --check"
  - "nosetests pysmt -v"
