jobs:
- job: 'Ubuntu16All'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py27All:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "all"
      Py37All:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "all"
      Py27Cython:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
      Py37Cython:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
      Py27GMPy:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_GMPY: "TRUE"
      Py37GMPy:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_GMPY: "TRUE"
      Py27CythonGMPy:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
        PYSMT_GMPY: "TRUE"
      Py37CythonGMPy:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
        PYSMT_GMPY: "TRUE"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16Py27'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py27Yices:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "yices"
      Py27CVC4:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "cvc4"
      Py27Btor:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "btor"
      Py27Picosat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "picosat"
      Py27Bdd:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "bdd"
      Py27MsatWrap:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat_wrap"
      Py27Z3Wrap:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3_wrap"

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16PyPy2'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      PyPy2NoSolver:
        pypy_binary: 'pypy'
        PYTHON_VERSION: 'pypy'
        PYSMT_SOLVER: "None"
      PyPy2MsatWrap:
        pypy_binary: 'pypy'
        PYTHON_VERSION: 'pypy'
        PYSMT_SOLVER: "msat_wrap"
      PyPy2Z3Wrap:
        pypy_binary: 'pypy'
        PYTHON_VERSION: 'pypy'
        PYSMT_SOLVER: "z3_wrap"

  steps:
  - bash: |
      echo "##vso[task.setvariable variable=PATH]$(System.DefaultWorkingDirectory)/pypy.tmp/pypy/bin:$(PATH)"
  - bash: |
      mkdir pypy.tmp
      cd pypy.tmp
      curl --location --output archive https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-linux64.tar.bz2
      tar xvf archive
      rm archive
      mv ./* pypy
      cd ..
    displayName: 'Get PyPy'
  - bash: |
      type $(pypy_binary)
      $(pypy_binary) --version
    displayName: 'Check for PyPy'
  - bash: |
      curl --output pypy.tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
      $(pypy_binary) pypy.tmp/get-pip.py
    displayName: 'Get PIP'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16PyPy3'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      PyPy3NoSolver:
        pypy_binary: 'pypy3'
        PYTHON_VERSION: 'pypy3'
        PYSMT_SOLVER: "None"
      PyPy3MsatWrap:
        pypy_binary: 'pypy3'
        PYTHON_VERSION: 'pypy3'
        PYSMT_SOLVER: "msat_wrap"
      PyPy3Z3Wrap:
        pypy_binary: 'pypy3'
        PYTHON_VERSION: 'pypy3'
        PYSMT_SOLVER: "z3_wrap"

  steps:
  - bash: |
      echo "##vso[task.setvariable variable=PATH]$(System.DefaultWorkingDirectory)/pypy.tmp/pypy/bin:$(PATH)"
  - bash: |
      mkdir pypy.tmp
      cd pypy.tmp
      curl --location --output archive https://bitbucket.org/pypy/pypy/downloads/pypy3.5-v7.0.0-linux64.tar.bz2
      tar xvf archive
      rm archive
      mv ./* pypy
      cd ..
    displayName: 'Get PyPy'
  - bash: |
      type $(pypy_binary)
      $(pypy_binary) --version
    displayName: 'Check for PyPy'
  - bash: |
      curl --output pypy.tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
      $(pypy_binary) pypy.tmp/get-pip.py
    displayName: 'Get PIP'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16Py37'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"
      Py37Yices:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "yices"
      Py37CVC4:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "cvc4"
      Py37Btor:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "btor"
      Py37Picosat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "picosat"
      Py37Bdd:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "bdd"
      Py37MsatWrap:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat_wrap"
      Py37Z3Wrap:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3_wrap"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'OSX10_13'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"
      Py27Yices:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "yices"
      Py37Yices:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "yices"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_osx.sh
    displayName: 'Install and Test'



- job: 'Win2016'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - powershell: ci/install_win.ps1
    displayName: 'Install and Test'