jobs:
- job: 'Ubuntu16All'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py27All:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "all"
      Py37All:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "all"
      Py27Cython:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
      Py37Cython:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
      Py27GMPy:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_GMPY: "TRUE"
      Py37GMPy:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_GMPY: "TRUE"
      Py27CythonGMPy:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
        PYSMT_GMPY: "TRUE"
      Py37CythonGMPy:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
        PYSMT_CYTHON: "TRUE"
        PYSMT_GMPY: "TRUE"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16Py27'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py27Yices:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "yices"
      Py27CVC4:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "cvc4"
      Py27Btor:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "btor"
      Py27Picosat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "picosat"
      Py27Bdd:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "bdd"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'Ubuntu16Py37'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"
      Py37Yices:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "yices"
      Py37CVC4:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "cvc4"
      Py37Btor:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "btor"
      Py37Picosat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "picosat"
      Py37Bdd:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "bdd"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_linux.sh
    displayName: 'Install and Test'



- job: 'OSX10_13'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"
      Py27Yices:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "yices"
      Py37Yices:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "yices"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ci/install_osx.sh
    displayName: 'Install and Test'



- job: 'Win2016'
  condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Py27NoSolver:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "None"
      Py37NoSolver:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "None"
      Py27Msat:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "msat"
      Py37Msat:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "msat"
      Py27Z3:
        python.version: '2.7'
        PYTHON_VERSION: '2.7'
        PYSMT_SOLVER: "z3"
      Py37Z3:
        python.version: '3.7'
        PYTHON_VERSION: '3.7'
        PYSMT_SOLVER: "z3"

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - powershell: ci/install_win.ps1
    displayName: 'Install and Test'